name: 'Prompt Lint'
description: 'Lint AI prompts for quality — deterministic scoring, zero LLM calls. Exits non-zero if any prompt scores below threshold. Supports standard/strict/relaxed presets.'
author: 'Rishi Banerjee'
branding:
  icon: 'check-circle'
  color: 'purple'
inputs:
  files:
    description: 'Glob pattern for prompt files to lint'
    required: true
  threshold:
    description: 'Minimum quality score (0-100). Optional — overrides strictness if set.'
    required: false
  strictness:
    description: 'Preset: standard (60), strict (75), relaxed (40). Ignored if threshold is set.'
    required: false
    default: 'standard'
  version:
    description: 'npm version to install (optional). If omitted, uses the action tag reference.'
    required: false
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: |
        VERSION="${{ inputs.version }}"
        if [ -z "$VERSION" ]; then VERSION="${{ github.action_ref }}"; fi
        # Strip leading 'v' (git tag v2.3.0 → npm 2.3.0)
        VERSION="${VERSION#v}"
        # Build CLI args with proper quoting (bash array)
        ARGS=(--file "${{ inputs.files }}")
        if [ -n "${{ inputs.threshold }}" ]; then
          ARGS+=(--threshold "${{ inputs.threshold }}")
        elif [ "${{ inputs.strictness }}" = "strict" ]; then
          ARGS+=(--strict)
        elif [ "${{ inputs.strictness }}" = "relaxed" ]; then
          ARGS+=(--relaxed)
        fi
        # Local checkout fallback (uses: ./ in self-tests)
        if [ -z "$VERSION" ] && [ -f "$GITHUB_ACTION_PATH/bin/lint.js" ] && [ -f "$GITHUB_ACTION_PATH/dist/src/lint-cli.js" ]; then
          node "$GITHUB_ACTION_PATH/bin/lint.js" "${ARGS[@]}"
          exit $?
        fi
        # Fail fast on empty version
        if [ -z "$VERSION" ]; then
          echo "::error::Could not resolve npm version. Set the 'version' input explicitly (e.g., version: '3.2.0')."
          exit 2
        fi
        # Accept only: major (2), or exact semver (2.3.0). Reject partial (2.3) and SHAs.
        if ! echo "$VERSION" | grep -qE '^([0-9]+|[0-9]+\.[0-9]+\.[0-9]+)$'; then
          echo "::error::Invalid version '${VERSION}'. Use a tag like @v3 or @v3.2.0, or set 'version' input (e.g., version: '3.2.0')."
          exit 2
        fi
        # npx can't run secondary bins — install to deterministic path and use node_modules/.bin
        INSTALL_DIR="${RUNNER_TEMP:-/tmp}/prompt-lint-$$"
        rm -rf "$INSTALL_DIR"
        npm install --prefix "$INSTALL_DIR" "claude-prompt-optimizer-mcp@${VERSION}" --no-save --ignore-scripts 2>&1
        "$INSTALL_DIR/node_modules/.bin/prompt-lint" "${ARGS[@]}"
      shell: bash
